config/routes.rb
Rails.application.routes.draw do
  resources :words
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "words#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service_object/http_request_service.rb
class ServiceObject::HttpRequestService
  def self.http_get_request(word)
    result = {
      "status_code" => 0,
      "definition" => "N/A",
      "message" => ""
    }
    headers = { 
      "app_id" => ENV["APP_ID"],
      "app_key" => ENV["APP_KEY"]
    }
    begin 
      response = HTTParty.get(
        "https://od-api.oxforddictionaries.com/api/v2/words/en-gb?q=" + word,
        :headers => headers
      )
      result["status_code"] = response.code
      case result["status_code"]
      when 200
        hash = JSON.parse(response.body)
        result["message"] = "Word was found"
        result["definition"] = hash['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]
        return result
      when 400
        result["message"] = "Bad Request"
        return result
      when 403
        result["message"] = "Authentication failed"
        return result
      when 404
        result["message"] = "Word Not Found"
        return result
      when 414
        result["message"] = "Request URI Too Long"
        return result
      when 500
        result["message"] = "Internal Server Error"
        return result
      when 502
        result["message"] = "Bad Gateway"
        return result
      when 503
        result["message"] = "Service Unavailable"
        return result
      when 504
        result["message"] = "Gateway timeout"
        return result
      end
      rescue HTTParty::Error => error
        Rails.logger.fatal error.inspect
      rescue => error
        Rails.logger.fatal error.inspect
      result["message"] = error.inspect
      return result
    end
  end
end

app/models/service_object/oxford_api.rb
class ServiceObject::OxfordApi
  def self.get_definition(word)
    result = {
      "status_code" => 0,
      "definition" => "N/A",
      "message" => ""
    }
    # important, headers required to make request to the oxford API
    headers = { 
      "app_id" => ENV["APP_ID"],
      "app_key" => ENV["APP_KEY"]
    }
    begin 
      response = HTTParty.get(
        "https://od-api.oxforddictionaries.com/api/v2/words/en-gb?q=" + word,
        :headers => headers
      )
      result["status_code"] = response.code
      # Handle all oxford API's status codes
      case result["status_code"]
      when 200
        hash = JSON.parse(response.body)
        result["message"] = "Word was found"
        # The definiton of a word will be the first available definiton, even though a word could have multiple definitions
        # Do we really need them all for now?
        result["definition"] = hash['results'][0]['lexicalEntries'][0]['entries'][0]['senses'][0]['definitions'][0]
        return result
      when 400
        result["message"] = "Bad Request"
        return result
      when 403
        result["message"] = "Authentication failed"
        return result
      when 404
        result["message"] = "Word Not Found"
        return result
      when 414
        result["message"] = "Request URI Too Long"
        return result
      when 500
        result["message"] = "Internal Server Error"
        return result
      when 502
        result["message"] = "Bad Gateway"
        return result
      when 503
        result["message"] = "Service Unavailable"
        return result
      when 504
        result["message"] = "Gateway timeout"
        return result
      end
      # Handling and logging exceptions on the most likely to fail part of the code
      rescue HTTParty::Error => error
        Rails.logger.fatal error.inspect
      rescue => error
        Rails.logger.fatal error.inspect
      result["message"] = error.inspect
      return result
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  validates :name, presence: true
  validates :definition, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.limit(5).all.order("created_at DESC")
    @word = Word.new
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)
    # Using service object to maintain thin controllers and models approach
    result = ServiceObject::OxfordApi.get_definition(@word.name)
    @word.definition = result["definition"]
    respond_to do |format|
      if @word.save and result["status_code"] == 200
        format.html { redirect_to root_path, notice: result["message"] }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { redirect_to root_path, alert: result["message"] }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:name, :definition).with_defaults(definition: "default definition.")
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dictionary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
    <nav class="navbar is-black">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5">Oxford dictionary interface</h1>
  		<% end %>
  	 </div>
  	</nav>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<%= simple_form_for(@word) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :name, 
        label: "Search Word",
        input_html: { class: "textfield" },
        required: true,
        wrapper: false,
        label_html: { class: "label" },
        placeholder: "Enter Word"%>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info is-small", value: "Search" %>
<% end %>

app/views/words/_history.html.erb
<div class="row">
  <% @words.each do |word| %>
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= word.name %></strong>
            <br>
            <%= word.definition %>
          </p>
        </div>
      </div>
    </article>
  <% end %>
</div>

app/views/words/_search.html.erb
<div class="row is-one-quarter">
  <article class="media">
      <div class="media-content">
        <div class="content">
          <%= render 'words/form' %>
        </div>
      </div>
    </article>
</div>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<section class="section">
  <div class="container">
    <div class="rows">
      <%= render 'search' %>
      <br/>
      <h1><strong>Searched words:</strong></h1>
      <br/>
      <%= render 'history' %>
    </div>
  </div>
</section>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word.name %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @word.definition %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>